; mod.ini

[Constants]
global $self_depth = 1
global $region_type = 0

global $walls_enabled = 1
global $terrain_seen = 0

global $cb0_offset = 0
global $cb0_size = 0

global $cb1_offset = 0
global $cb1_size = 0

[KeyFullBorder]
key = VK_MENU VK_NUMPAD9
type = cycle
$self_depth = 0,1

[ResourceWallVB]
type = Buffer
stride = 20
filename = Buffers/walls_vb.buf


[ResourceWallIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffers/walls_ib.buf

[ResourceWallDepth]
type = Texture2D
width = 1920
height = 1080
format = DXGI_FORMAT_D32_FLOAT
mips = 1
array = 1
msaa = 1
bind_flags = depth_stencil


[ResourceTerrainCB0]

[ResourceTerrainCB1]


[ShaderOverrideTerrainCapture]

hash = 5204669b553b0cda
allow_duplicate_hash = true

run = CommandListCaptureTerrainCamera


[CommandListCaptureTerrainCamera]

$terrain_seen = 1

$cb0_offset = vs-cb0->Offset
$cb0_size = vs-cb0->Size
ResourceTerrainCB0 = ref vs-cb0

$cb1_offset = vs-cb1->Offset
$cb1_size = vs-cb1->Size
ResourceTerrainCB1 = ref vs-cb1

[CustomShaderValley4Walls]

vs = Shaders/wall_vs.hlsl
ps = Shaders/wall_ps.hlsl

hs = null
ds = null
gs = null

topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA

if $self_depth == 1
	depth_enable = true
	depth_write_mask = all
	depth_func = greater_equal
endif

run = BuiltInCommandListUnbindAllRenderTargets

o0 = set_viewport bb
if $self_depth == 1
	oD = ResourceWallDepth

	clear = ResourceWallDepth
endif

vb0 = ref ResourceWallVB
ib = ref ResourceWallIB

vs-cb0 = ref ResourceTerrainCB0->Region($cb0_offset, $cb0_size)
vs-cb1 = ref ResourceTerrainCB1->Region($cb1_offset, $cb1_size)

drawindexed = 6288, 0, 0


[Present]

if $walls_enabled && $terrain_seen
	run = CustomShaderValley4Walls
endif

post $terrain_seen = 0