; For 1.4

[Constants]
global $InPauseMenu = 0
global $InProfile = 0

[Present]
post $InPauseMenu = 0
post $InProfile = 0

; Match Hashes -----------------------------

[ShaderOverride_MatchPause]
hash = c38bf791503255aa
allow_duplicate_hash = overrule
$InPauseMenu = 1

[ShaderOverride_MatchProfile]
hash = 0455377ec18d59bc
allow_duplicate_hash = overrule
$InProfile = 1

; Hide UID ---------------------------------

[TextureOverride_MainUID]
hash = f073fb8b
match_first_index = 18
match_index_count = 120
handling = skip

[TextureOverride_PauseUID1]
hash = 1ad9c553
match_first_index = 1734
match_index_count = 108
if $InPauseMenu == 1
	handling = skip
endif

[TextureOverride_PauseUID3]
hash = 1ad9c553
match_first_index = 1740
match_index_count = 108
if $InPauseMenu == 1
	handling = skip
endif

[TextureOverride_ProfileUID]
hash = a34f201c
match_index_count = 66
if $InProfile == 1
	handling = skip
endif

[TextureOverride_ProfileName]
hash = c0cb916b
match_index_count = 102
if $InProfile == 1
	handling = skip
endif