; For 1.4

[Constants]
global $NoFoliage = 0

; Keybind ----------------------------------

[KeyFoliage]
key = VK_MENU VK_NUMPAD5
type = cycle
$NoFoliage = 0,1

; No Foliage -------------------------------

; Removes LOD dithering but causes severe motion vector artifacts
; [ShaderOverrideFoliage0]
; hash = efaae32cb873d5b7
; allow_duplicate_hash = true
; run = CommandListFoliageShader

[ShaderOverrideFoliage1]
hash = 80e99252170ac2ff
run = CommandListFoliageShader

[ShaderOverrideFoliage2]
hash = c7c0343a36285f20
run = CommandListFoliageShader

[ShaderOverrideFoliage3]
hash = d317c1acafd3119d
run = CommandListFoliageShader

[ShaderOverrideFoliage4]
hash = f1a85f4972982608
run = CommandListFoliageShader

[ShaderOverrideFoliage5]
hash = fb3e3687f6f13d21
run = CommandListFoliageShader

[ShaderOverrideFoliage6]
hash = 348034e5eb5d0798
run = CommandListFoliageShader

[ShaderOverrideFoliage7]
hash = 6bc5bd488c8043ff
run = CommandListFoliageShader

[ShaderOverrideFoliage8]
hash = 99bcebc14e45250a
run = CommandListFoliageShader

[ShaderOverrideFoliage9]
hash = c48cead99cd3f6b3
run = CommandListFoliageShader

[ShaderOverrideFoliage10]
hash = 5bfd243b804318ca
run = CommandListFoliageShader

; CommandList -------------------------

[CommandListFoliageShader]
if $NoFoliage == 1
	handling = skip
endif
