; For 1.4

[Constants]
global $UnlitMode = 0

; Keybind ----------------------------------

[KeyUnlitMode]
key = VK_MENU VK_NUMPAD4
type = cycle
$UnlitMode = 0,1

; Unlit Mode -------------------------------

[ShaderOverrideUnlit_Bloom01]
hash = fea5ae37baee4633
if $UnlitMode == 1
	handling = skip
endif

[ShaderOverrideUnlit_VolumetricFog01]
hash = 5bffbe3f9080ee1b
if $UnlitMode == 1
	handling = skip
endif

[ShaderOverrideUnlit_743f991c236b6dde]
hash = 743f991c236b6dde
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_743f991c236b6dde
endif

[CustomShaderUnlit_743f991c236b6dde]
ps = Shaders/Unlit/Terrain_743f991c236b6dde.txt
draw = from_caller

[ShaderOverrideUnlit_b8360398f113f945]
hash = b8360398f113f945
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_b8360398f113f945
endif

[CustomShaderUnlit_b8360398f113f945]
ps = Shaders/Unlit/Terrain_b8360398f113f945.txt
draw = from_caller

[ShaderOverrideUnlit_30462d509b56535f]
hash = 30462d509b56535f
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_30462d509b56535f
endif

[CustomShaderUnlit_30462d509b56535f]
ps = Shaders/Unlit/Terrain_30462d509b56535f.txt
draw = from_caller

[ShaderOverrideUnlit_addb4925f6e279b8]
hash = addb4925f6e279b8
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_addb4925f6e279b8
endif

[CustomShaderUnlit_addb4925f6e279b8]
ps = Shaders/Unlit/Terrain_addb4925f6e279b8.txt
draw = from_caller

[ShaderOverrideUnlit_955aa6eb61756d0c]
hash = 955aa6eb61756d0c
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_955aa6eb61756d0c
endif

[CustomShaderUnlit_955aa6eb61756d0c]
ps = Shaders/Unlit/Terrain_955aa6eb61756d0c.txt
draw = from_caller

[ShaderOverrideUnlit_17b280fb09bf16fd]
hash = 17b280fb09bf16fd
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_17b280fb09bf16fd
endif

[CustomShaderUnlit_17b280fb09bf16fd]
ps = Shaders/Unlit/Terrain_17b280fb09bf16fd.txt
draw = from_caller

[ShaderOverrideUnlit_530cf926c33e99ee]
hash = 530cf926c33e99ee
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_530cf926c33e99ee
endif

[CustomShaderUnlit_530cf926c33e99ee]
ps = Shaders/Unlit/Terrain_530cf926c33e99ee.txt
draw = from_caller

[ShaderOverrideUnlit_bb9293bfbf23a3c5]
hash = bb9293bfbf23a3c5
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_bb9293bfbf23a3c5
endif

[CustomShaderUnlit_bb9293bfbf23a3c5]
ps = Shaders/Unlit/Terrain_bb9293bfbf23a3c5.txt
draw = from_caller

[ShaderOverrideUnlit_5e5271b322c7bd5c]
hash = 5e5271b322c7bd5c
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_5e5271b322c7bd5c
endif

[CustomShaderUnlit_5e5271b322c7bd5c]
ps = Shaders/Unlit/Terrain_5e5271b322c7bd5c.txt
draw = from_caller

[ShaderOverrideUnlit_6f33660185243d05]
hash = 6f33660185243d05
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_6f33660185243d05
endif

[CustomShaderUnlit_6f33660185243d05]
ps = Shaders/Unlit/Terrain_6f33660185243d05.txt
draw = from_caller

[ShaderOverrideUnlit_37eacbc3c84bb392]
hash = 37eacbc3c84bb392
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_37eacbc3c84bb392
endif

[CustomShaderUnlit_37eacbc3c84bb392]
ps = Shaders/Unlit/Terrain_37eacbc3c84bb392.txt
draw = from_caller

[ShaderOverrideUnlit_e5c79df0d5b00481]
hash = e5c79df0d5b00481
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_e5c79df0d5b00481
endif

[CustomShaderUnlit_e5c79df0d5b00481]
ps = Shaders/Unlit/Terrain_e5c79df0d5b00481.txt
draw = from_caller

[ShaderOverrideUnlit_e02f4d6993f80551]
hash = e02f4d6993f80551
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_e02f4d6993f80551
endif

[CustomShaderUnlit_e02f4d6993f80551]
ps = Shaders/Unlit/Foliage_e02f4d6993f80551.txt
draw = from_caller

[ShaderOverrideUnlit_c2f0f0165b78a730]
hash = c2f0f0165b78a730
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_c2f0f0165b78a730
endif

[CustomShaderUnlit_c2f0f0165b78a730]
ps = Shaders/Unlit/Foliage_c2f0f0165b78a730.txt
draw = from_caller

[ShaderOverrideUnlit_b564381e16bd84f4]
hash = b564381e16bd84f4
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_b564381e16bd84f4
endif

[CustomShaderUnlit_b564381e16bd84f4]
ps = Shaders/Unlit/Foliage_b564381e16bd84f4.txt
draw = from_caller

[ShaderOverrideUnlit_2c0a0efb51eb7e5b]
hash = 2c0a0efb51eb7e5b
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_2c0a0efb51eb7e5b
endif

[CustomShaderUnlit_2c0a0efb51eb7e5b]
ps = Shaders/Unlit/Foliage_2c0a0efb51eb7e5b.txt
draw = from_caller

[ShaderOverrideUnlit_a990d7a6eca08f04]
hash = a990d7a6eca08f04
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_a990d7a6eca08f04
endif

[CustomShaderUnlit_a990d7a6eca08f04]
ps = Shaders/Unlit/Foliage_a990d7a6eca08f04.txt
draw = from_caller

[ShaderOverrideUnlit_3130bda32c0d1261]
hash = 3130bda32c0d1261
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_3130bda32c0d1261
endif

[CustomShaderUnlit_3130bda32c0d1261]
ps = Shaders/Unlit/Foliage_3130bda32c0d1261.txt
draw = from_caller

[ShaderOverrideUnlit_b142c026a459d8c6]
hash = b142c026a459d8c6
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_b142c026a459d8c6
endif

[CustomShaderUnlit_b142c026a459d8c6]
ps = Shaders/Unlit/Foliage_b142c026a459d8c6.txt
draw = from_caller

[ShaderOverrideUnlit_4009fb12d319f84c]
hash = 4009fb12d319f84c
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_4009fb12d319f84c
endif

[CustomShaderUnlit_4009fb12d319f84c]
ps = Shaders/Unlit/Foliage_4009fb12d319f84c.txt
draw = from_caller

[ShaderOverrideUnlit_4d4aeaba77c8835c]
hash = 4d4aeaba77c8835c
if $UnlitMode == 1
	handling = skip
	run = CustomShaderUnlit_4d4aeaba77c8835c
endif

[CustomShaderUnlit_4d4aeaba77c8835c]
ps = Shaders/Unlit/Water_4d4aeaba77c8835c.txt
draw = from_caller