import bpy
import struct
import os


# ============================================================
# CONFIGURATION
# ============================================================

OUTPUT_DIR = r"C:\Users\RedCraft86\Desktop\Endfield\AirWalls"

# Keep False with the current shader, because wall_vs.hlsl already performs
# Blender (X,Y,Z) -> Endfield (X,Z,-Y).
AXIS_SWAP = False

# Self-depth buffer dimensions used by the current working mod.
DEPTH_WIDTH = 1920
DEPTH_HEIGHT = 1080


# ============================================================
# GENERATED SHADERS
# ============================================================

WALL_VS = r'''// Shaders/wall_vs.hlsl

cbuffer TerrainCB0 : register(b0)
{
    float4 cb0[82];
};

cbuffer TerrainCB1 : register(b1)
{
    float4 cb1[20];
};

struct VSOut
{
    float4 pos : SV_Position;
    float2 uv : TEXCOORD0;
    nointerpolation float dist : TEXCOORD1;
};

VSOut main(
    float3 inPos : POSITION,
    float2 inUV : TEXCOORD0
)
{
    VSOut o;

    float3 gamePos = float3(
         inPos.x,
         inPos.z,
        -inPos.y
    );

    float3 relativePos =
        gamePos - cb0[44].xyz;

    o.dist = length(relativePos);

    float4 clip =
          cb0[32] * relativePos.x
        + cb0[33] * relativePos.y
        + cb0[34] * relativePos.z
        + cb0[35];

    float2 jitter =
        cb1[19].zw * clip.w;

    clip.xy +=
        -jitter * float2(2.0, -2.0);

    clip.y = -clip.y;

    o.pos = clip;
    o.uv = inUV;

    return o;
}
'''

WALL_PS = r'''float4 main(
    float4 pos : SV_Position,
    float2 uv  : TEXCOORD0,
    nointerpolation float dist : TEXCOORD1
) : SV_Target
{
    const float MAX_DIST = 200.0;
    if (dist > MAX_DIST)
        discard;

    float3 bary = float3(
        uv.x,
        uv.y,
        1.0 - uv.x - uv.y
    );

    float3 derivative =
        fwidth(bary);

    const float INNER_WIDTH = 1.5;
    const float OUTER_WIDTH = 2.0;

    float3 interiorMask =
        smoothstep(
            derivative * INNER_WIDTH,
            derivative * OUTER_WIDTH,
            bary
        );

    float interior =
        min(
            interiorMask.x,
            min(
                interiorMask.y,
                interiorMask.z
            )
        );

    float edge =
        1.0 - interior;

    float4 faceColor = float4(
        0.0,
        1.0,
        1.0,
        0.1
    );

    float4 edgeColor = float4(
        0.0,
        0.1,
        0.3,
        0.5
    );

    return lerp(
        faceColor,
        edgeColor,
        edge
    );
}
'''


def build_mod_ini(index_count):
    return f'''; mod.ini
; Generated by ExportAirWalls.py
; Indices: {index_count}
; Triangles: {index_count // 3}

[Constants]
global $self_depth = 1

global $walls_enabled = 1
global $terrain_seen = 0

global $cb0_offset = 0
global $cb0_size = 0

global $cb1_offset = 0
global $cb1_size = 0

[KeyFullBorder]
key = VK_MENU VK_NUMPAD9
type = cycle
$self_depth = 0,1

[ResourceWallVB]
type = Buffer
stride = 20
filename = Buffers/walls_vb.buf

[ResourceWallIB]
type = Buffer
format = DXGI_FORMAT_R32_UINT
filename = Buffers/walls_ib.buf

[ResourceWallDepth]
type = Texture2D
width = {DEPTH_WIDTH}
height = {DEPTH_HEIGHT}
format = DXGI_FORMAT_D32_FLOAT
mips = 1
array = 1
msaa = 1
bind_flags = depth_stencil

[ResourceTerrainCB0]

[ResourceTerrainCB1]

[ShaderOverrideTerrainCapture]
hash = 5204669b553b0cda
run = CommandListCaptureTerrainCamera

[CommandListCaptureTerrainCamera]
$terrain_seen = 1

$cb0_offset = vs-cb0->Offset
$cb0_size = vs-cb0->Size
ResourceTerrainCB0 = ref vs-cb0

$cb1_offset = vs-cb1->Offset
$cb1_size = vs-cb1->Size
ResourceTerrainCB1 = ref vs-cb1

[CustomShaderAirWalls]
vs = Shaders/wall_vs.hlsl
ps = Shaders/wall_ps.hlsl

hs = null
ds = null
gs = null

topology = triangle_list
blend = ADD SRC_ALPHA INV_SRC_ALPHA

if $self_depth == 1
    depth_enable = true
    depth_write_mask = all
    depth_func = greater_equal
endif

run = BuiltInCommandListUnbindAllRenderTargets

o0 = set_viewport bb
if $self_depth == 1
    oD = ResourceWallDepth
    clear = ResourceWallDepth
endif

vb0 = ref ResourceWallVB
ib = ref ResourceWallIB

vs-cb0 = ref ResourceTerrainCB0->Region($cb0_offset, $cb0_size)
vs-cb1 = ref ResourceTerrainCB1->Region($cb1_offset, $cb1_size)

drawindexed = {index_count}, 0, 0

[Present]
if $walls_enabled && $terrain_seen
    run = CustomShaderAirWalls
endif

post $terrain_seen = 0
'''


# ============================================================
# GET ACTIVE OBJECT
# ============================================================

obj = bpy.context.active_object

if obj is None:
    raise RuntimeError("No active object. Select the wall mesh first.")

if obj.type != "MESH":
    raise RuntimeError(f"Active object '{obj.name}' is not a mesh.")


# ============================================================
# GET MESH
# ============================================================

mesh = obj.data
mesh.calc_loop_triangles()

vertices = []
indices = []


# ============================================================
# EXPORT TRIANGLES
# ============================================================

for tri in mesh.loop_triangles:
    for corner, loop_idx in enumerate(tri.loops):
        vert_idx = mesh.loops[loop_idx].vertex_index

        # Export Blender world-space coordinates. The VS performs the
        # Blender -> Endfield coordinate conversion.
        co = obj.matrix_world @ mesh.vertices[vert_idx].co

        if AXIS_SWAP:
            x = co.x
            y = co.z
            z = -co.y
        else:
            x = co.x
            y = co.y
            z = co.z

        # Per-triangle barycentric-style UVs used by wall_ps.hlsl.
        if corner == 0:
            u, v = 0.0, 0.0
        elif corner == 1:
            u, v = 1.0, 0.0
        else:
            u, v = 0.0, 1.0

        vertices.append((float(x), float(y), float(z), float(u), float(v)))

        # Every triangle corner is exported as a unique vertex. Therefore
        # the number of indices is exactly the DrawIndexed IndexCount.
        indices.append(len(vertices) - 1)


# ============================================================
# COUNTS
# ============================================================

vertex_count = len(vertices)
index_count = len(indices)
triangle_count = index_count // 3

if vertex_count == 0:
    raise RuntimeError("The selected mesh contains no triangles.")

if index_count % 3 != 0:
    raise RuntimeError("Index count is not divisible by 3.")


# ============================================================
# CREATE COMPLETE MOD DIRECTORY
# ============================================================

buffers_dir = os.path.join(OUTPUT_DIR, "Buffers")
shaders_dir = os.path.join(OUTPUT_DIR, "Shaders")

os.makedirs(buffers_dir, exist_ok=True)
os.makedirs(shaders_dir, exist_ok=True)

vb_path = os.path.join(buffers_dir, "walls_vb.buf")
ib_path = os.path.join(buffers_dir, "walls_ib.buf")
mod_path = os.path.join(OUTPUT_DIR, "mod.ini")
vs_path = os.path.join(shaders_dir, "wall_vs.hlsl")
ps_path = os.path.join(shaders_dir, "wall_ps.hlsl")


# ============================================================
# WRITE BUFFERS
# ============================================================

with open(vb_path, "wb") as f:
    for vertex in vertices:
        f.write(struct.pack("<5f", *vertex))

with open(ib_path, "wb") as f:
    for index in indices:
        f.write(struct.pack("<I", index))


# ============================================================
# WRITE MOD + SHADERS
# ============================================================

with open(mod_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(build_mod_ini(index_count))

with open(vs_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(WALL_VS)

with open(ps_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(WALL_PS)


# ============================================================
# VALIDATION
# ============================================================

actual_vb_size = os.path.getsize(vb_path)
actual_ib_size = os.path.getsize(ib_path)

expected_vb_size = vertex_count * 20
expected_ib_size = index_count * 4

if actual_vb_size != expected_vb_size:
    raise RuntimeError(
        "Vertex buffer size does not match the expected 20-byte vertex stride."
    )

if actual_ib_size != expected_ib_size:
    raise RuntimeError(
        "Index buffer size does not match the expected 4-byte index format."
    )


# ============================================================
# REPORT
# ============================================================

print()
print("========================================")
print("EFMI AIR WALL MOD EXPORT")
print("========================================")
print(f"Object:       {obj.name}")
print(f"Vertices:     {vertex_count}")
print(f"Indices:      {index_count}")
print(f"Triangles:    {triangle_count}")
print("Stride:       20 bytes")
print(f"Axis swap:    {AXIS_SWAP}")
print(f"Draw call:    drawindexed = {index_count}, 0, 0")
print("========================================")
print()
print("Generated:")
print(f"  {mod_path}")
print(f"  {vb_path}")
print(f"  {ib_path}")
print(f"  {vs_path}")
print(f"  {ps_path}")
print()
print("Export successful.")
