; For 1.4

[Constants]
global $FullBorder = 0
global $FullAICTiles = 0

; Keybinds ---------------------------------

[KeyFullBorder]
key = VK_MENU VK_NUMPAD1
type = cycle
$FullBorder = 0,1

[KeyFullAICTiles]
key = VK_MENU VK_NUMPAD2
type = cycle
$FullAICTiles = 0,1

; FEATURES ---------------------------------

; Full Region Borders ----------------------

[ShaderOverrideFullBorder]
hash = b201629ad4b4e5da
if $FullBorder == 1
	handling = skip
	run = CustomShaderFullBorder
endif

[CustomShaderFullBorder]
ps = Shaders/FullBorder_b201629ad4b4e5da.txt
draw = from_caller

; Full AIC Tiles ---------------------------

[ShaderOverrideFullAICTiles]
hash = 700e02fb213abdcf
if $FullAICTiles == 1
	handling = skip
	run = CustomShaderFullAICTiles
endif

[CustomShaderFullAICTiles]
ps = Shaders/FullAICTiles_700e02fb213abdcf.txt
draw = from_caller
