; For 1.4

[Constants]
global $NoGameUI = 0

; Keybind ----------------------------------

[KeyGameUI]
key = VK_MENU VK_NUMPAD7
type = cycle
$NoGameUI = 0,1

; No Game UI -------------------------------

[ShaderOverrideGameUI1]
hash = 0455377ec18d59bc
run = CommandListGameUIShader

[ShaderOverrideGameUI2]
hash = 54f066aab750db23
run = CommandListGameUIShader

[ShaderOverrideGameUI3]
hash = 8459ccc3b1316383
run = CommandListGameUIShader

[ShaderOverrideGameUI4]
hash = f2dc00276bab2d84
run = CommandListGameUIShader

[ShaderOverrideGameUI5]
hash = bb49284d2be9e985
run = CommandListGameUIShader

[ShaderOverrideGameUI6]
hash = bd7427f0206c4436
run = CommandListGameUIShader

[ShaderOverrideGameUI7]
hash = dae7c6cdd8a78d51
run = CommandListGameUIShader

[ShaderOverrideGameUI8]
hash = c5cac33f8155ae72
run = CommandListGameUIShader

[ShaderOverrideGameUI9]
hash = 859100cba35137a1
run = CommandListGameUIShader

[ShaderOverrideGameUI10]
hash = 01259601012f89c3
run = CommandListGameUIShader

; CommandList -------------------------

[CommandListGameUIShader]
if $NoGameUI == 1
	handling = skip
endif
