; For 1.4

[Constants]
global $RCEFVision = 0

; Keybind ----------------------------------

[KeyRCEFVision]
key = VK_MENU VK_END
type = toggle
run = CommandListKeybinds

; Keybind Screen ---------------------------

[CommandListKeybinds]
pre Resource\ShaderFixes\help.ini\Help = ref ResourceKeybindsFull
pre Resource\ShaderFixes\help.ini\Params = ref ResourceParamsFull
pre run = CustomShader\ShaderFixes\help.ini\FormatText
post Resource\ShaderFixes\help.ini\Help = null

[ResourceKeybindsFull]
type = buffer
format = R8_UINT
filename = _Keybinds.txt

[ResourceParamsFull]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.5 0.5 0.5 -0.5   1.0 0.7 0.2 1.0   0.0 0.0 0.0 0.7   0.01 0.01   2 2   0   1.2
;                  ^^^^Rectangle^^^ |   ^^^Colour^^^  |   Background    | ^Border^^ | ^ ^ | ^ |  ^-- font scale
;                  x1   y1  x2   y2 |  r   g   b   a  |  r   g   b   a  | horz vert |  ^  | ^------ text alignment: 0=left 1=center 2=right
;                    range -1:+1    |                 |  r   g   b   a  | horz vert |  ^----------- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom