; Fog Removal and Unlit Shaders for 1.4


[Constants]
global $RCEF = 0

[KeyRCEF]
key = page_down
type = cycle
$RCEF = 0,1,2

; Overrides ---------------------------

[ShaderOverride_Hook]
; Irrelevant shader, controls the font
; This is only here for the mod to hook into shader loading and apply the xy186 values
hash = 8459ccc3b1316383
allow_duplicate_hash = true
x186 = $RCEF == 1
y186 = $RCEF == 2

[ShaderOverride_SunGlare01]
hash = fea5ae37baee4633
allow_duplicate_hash = true
run = CommandListWhenEnabled

[ShaderOverride_SunGlare02]
hash = 7e075b5cb2cc6462
allow_duplicate_hash = true
run = CommandListWhenEnabled

[ShaderOverride_Volumetric01]
hash = 5bffbe3f9080ee1b
allow_duplicate_hash = true
run = CommandListWhenEnabled

[ShaderOverride_Misc]
hash = 46e80a084c9de0fd
allow_duplicate_hash = true
run = CommandListWhenEnabled

; CommandList -------------------------

[CommandListWhenEnabled]
if $RCEF != 0
	handling = skip
endif